name: CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pipenv
                  pip install exceptiongroup
                  pip install -r requirements.txt
            - name: Run tests
              run: pytest
            - name: Rename to index.html
              run: |
                  cd report
                  mv pytest_html_report.html index.html
            - name: Deploy
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
                PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                PUBLISH_BRANCH: gh-pages  # default: gh-pages
                PUBLISH_DIR: report